import 'package:flutter/material.dart';
import 'package:dio/dio.dart';

void main() {
  runApp(MyApp());
}

class Autogenerated {
  int? id;
  int? userId;
  String? title;
  String? body;

  Autogenerated({this.id, this.userId, this.title, this.body});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    userId = json['user_id'];
    title = json['title'];
    body = json['body'];
  }
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final Dio dio = Dio();
  List<Autogenerated> posts = [];

  @override
  void initState() {
    super.initState();
    fetchPosts();
  }

  Future<void> fetchPosts() async {
    try {
      final response = await dio.get('https://gorest.co.in/public/v2/posts');

      if (response.statusCode == 200) {
        final List<dynamic> data = response.data;
        print("dataaaa,${response.data}");
        setState(() {
          posts.clear();
          posts
              .addAll(data.map((postJson) => Autogenerated.fromJson(postJson)));
        });
      } else {
        print('Failed to load posts');
      }
    } catch (e) {
      print('Error: $e');
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Posts'),
        ),
        body: ListView.builder(
          itemCount: posts.length,
          itemBuilder: (context, index) {
            return ListTile(
              title: Text(posts[index].title!),
              subtitle: Text(posts[index].body!),
              // You can customize the appearance and layout as needed
            );
          },
        ),
      ),
    );
  }
}